# Generated by Django 3.2.9 on 2021-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zackzorn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
