# Generated by Django 3.2.9 on 2021-11-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zackzorn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_designer',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='producer',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
