# Generated by Django 3.2.9 on 2021-11-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zackzorn', '0002_artist_artist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='MusicGenre',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('author', models.CharField(max_length=45)),
                ('pseudonym', models.CharField(max_length=45)),
                ('publisher', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('isbn', models.IntegerField()),
                ('img_url', models.CharField(max_length=45)),
                ('pages_total', models.IntegerField()),
                ('genre', models.ManyToManyField(to='zackzorn.BookGenre')),
            ],
        ),
    ]
