# Generated by Django 3.2.9 on 2021-11-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zackzorn', '0002_alter_band_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.ManyToManyField(blank=True, to='zackzorn.MusicGenre'),
        ),
    ]
