# Generated by Django 3.2.9 on 2021-11-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zackzorn', '0003_auto_20211107_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('event_type', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=45)),
                ('ticket_price', models.IntegerField()),
                ('description', models.TextField()),
                ('interviewee', models.CharField(max_length=45)),
                ('completed', models.BooleanField()),
                ('cancelled', models.BooleanField()),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zackzorn.band')),
            ],
        ),
    ]
